services:
  pocketbase:
    build: .
    container_name: canutin-pocketbase
    ports:
      - '42070:42070'
    volumes:
      - canutin-data:/app/pocketbase/pb_data
    environment:
      PUBLIC_DEMO_ENABLED: ${PUBLIC_DEMO_ENABLED:-false}
      PUBLIC_PLAUSIBLE_DOMAIN: ${PUBLIC_PLAUSIBLE_DOMAIN:-}
      PUBLIC_PLAUSIBLE_SCRIPT_URL: ${PUBLIC_PLAUSIBLE_SCRIPT_URL:-}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID:-}
      PLAID_SECRET: ${PLAID_SECRET:-}
      PLAID_ENV: ${PLAID_ENV:-}
    restart: unless-stopped

volumes:
  canutin-data:
