name: Tests

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: pocketbase/go.sum

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps chromium webkit

      - name: Run Playwright tests
        run: xvfb-run -a bun run test -- --project=mobile e2e/transactions.filtering.test.ts e2e/transactions.crud.test.ts e2e/securities.sorting.test.ts e2e/assets.sorting.test.ts --repeat-each=8
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() # Upload results even if tests fail
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 2
